kumuluzee:
  name: journaling-service
  env:
    name: dev
  version: 1.0.0
  metrics:
    web-instrumentation:
      - name: journaling-endpoint
        url-pattern: /journal
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://postgres:5432/postgres
      username: dbuser
      password: postgres
      max-pool-size: 20